#
#########################################
#  General SETTINGS
#########################################
#
title: General Settings
path: config
id: v_gcfg
icon: mdi:settings
panel: true
cards:
- type: horizontal-stack
  cards:
# COL 1
    - type: vertical-stack
      cards:
        - type: entities
          title: Automations
          show_header_toggle: false
          entities:
            - entity: input_boolean.lr_slow_dim
            - entity: input_boolean.sr_slow_dim
            - entity: input_boolean.br1_slow_dim
            - entity: input_boolean.br2_slow_dim
            - entity: input_boolean.hass_io_autobackup
            - type: divider
            - entity: input_boolean.valentine_lighting
            - entity: input_boolean.st_pattys_lighting
            - entity: input_boolean.easter_lighting
            - entity: input_boolean.memorial_day_lighting
            - entity: input_boolean.flag_day_lighting
            - entity: input_boolean.independence_day_lighting
            - entity: input_boolean.labor_day_lighting
            - entity: input_boolean.cancer_lighting
            - entity: input_boolean.halloween_lighting
            - entity: input_boolean.thanksgiving_lighting
            - entity: input_boolean.christmas_lighting
            
# COL 2
    - type: vertical-stack
      cards:
        - type: entities
          title: Settings
          show_header_toggle: false
          entities:
            - entity: input_select.season_holiday
#            - entity: input_boolean.enable_push_notifications
#            - entity: input_boolean.enable_prowl_notifications
#            - entity: input_boolean.mode_privacy
            - entity: input_boolean.battery_notifications
            - entity: input_boolean.sensor_reset_notifications
            - entity: input_boolean.system_alerts
            - entity: input_boolean.weather_alerts
            - entity: input_boolean.zone_alerts
            - entity: input_select.led_color
            - entity: input_number.led_strip_brightness
            - type: divider
            - entity: input_boolean.sandbox_testing
            - entity: input_boolean.trigger_sandbox
# COL 3
    - type: vertical-stack
      cards:
        - type: entities
          title: Motion Detection
          show_header_toggle: false
          entities:
            - entity: input_boolean.kit_motion_detected
            - entity: input_datetime.last_kitchen_motion
            - entity: input_select.kit_lights_auto_off
#            - entity: input_number.lights_auto_off_slider
            - entity: input_boolean.speak_kit_motion
            - type: divider
            - entity: input_boolean.lr_motion_detected
            - entity: input_datetime.last_livingrm_motion
            - entity: input_boolean.speak_lr_motion
#
        - type: entities
          title: Schedules
          show_header_toggle: false
          entities:
            - entity: input_datetime.recycle_alert_date
            - entity: sensor.day_of_year
            - entity: sensor.week_of_year
#
#            - entity: input_number.lights_lux_high_value
#            - entity: input_number.lights_max_value
#            - entity: input_number.lights_min_value
#            - entity: input_number.lights_step_value
#            - entity: input_select.indoor_camera_feed
#            - entity: input_select.outdoor_camera_feed
#
