#
#########################################
#  General SETTINGS
#########################################
#
title: General Settings
path: config
id: v_gcfg
icon: mdi:settings
panel: true
cards:
- type: horizontal-stack
  cards:
# COL 1
    - type: vertical-stack
      cards:
        - type: entities
          title: Automations
          show_header_toggle: false
          entities:
            - entity: input_boolean.enable_hassio_autobackup
            - entity: input_boolean.enable_br1_slow_dim
            - entity: input_boolean.enable_br2_slow_dim
            - entity: input_boolean.close_garage_doors_in_rain
            - entity: input_boolean.enable_lr_slow_dim
            - entity: input_boolean.enable_sr_slow_dim

# COL 2
    - type: vertical-stack
      cards:
        - type: entities
          title: Seasonal
          show_header_toggle: false
          entities:
            - entity: input_select.season_holiday
            - entity: input_boolean.enable_new_years_lighting
            - entity: input_boolean.enable_valentine_lighting
            - entity: input_boolean.enable_pattys_lighting
            - entity: input_boolean.enable_easter_lighting
            - entity: input_boolean.enable_memorial_lighting
            - entity: input_boolean.enable_flag_day_lighting
            - entity: input_boolean.enable_independence_lighting
            - entity: input_boolean.enable_labor_lighting
            - entity: input_boolean.enable_cancer_lighting
            - entity: input_boolean.enable_halloween_lighting
            - entity: input_boolean.enable_thanksgiving_lighting
            - entity: input_boolean.enable_christmas_lighting
#
# COL 3
    - type: vertical-stack
      cards:
        - type: entities
          title: Notifications
          show_header_toggle: false
          entities:
            - entity: input_boolean.daily_briefing_art
            - entity: input_boolean.daily_briefing_steff
            - entity: input_boolean.enable_battery_notifications
            - entity: input_boolean.enable_sensor_notifications
            - entity: input_boolean.enable_system_alerts
            - entity: input_boolean.enable_weather_alerts
            - entity: input_boolean.zone_alerts
#
# COL 4
    - type: vertical-stack
      cards:
        - type: entities
          title: User Inputs
          show_header_toggle: false
          entities:
            - entity: input_select.kit_lights_auto_off
            - entity: input_select.days_to_display
              name: Birthady/Anniversary Day to Display
            - type: divider
            - entity: input_select.led_color
              name: Flux LED TV Backlighting
            - entity: input_number.led_strip_brightness
#
