title: My Home Assistant
excluded_entities:
  - weblink.router
views:
#  View 1
  - title: Home
    id: v_home
    background: radial-gradient(crimson, skyblue)
    cards:
#     Card 1
      - type: entity-filter
        id: c_t1c1
        entities:
          - device_tracker.artsiphone8
          - device_tracker.steffsiphone8
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home
#     Card 2
        # The picture entity card will represent an entity with a picture
      - type: picture-entity
        id: c_t1c2
        image: https://www.home-assistant.io/images/default-social.png
        entity: light.office_light_223
#     Card 3
      - type: light
        id: c_t1c3
        entity: light.office_light_223
#     Card 4
      - type: weather-forecast
        id: c_t1c4
        entity: weather.dark_sky
#  View 2
  - icon: mdi:home-assistant
    title: Second view
    id: v_tab2
    cards:
#     Card 1
        # Entities card will take a list of entities and show their state.
      - type: entities
        id: c_t2c1
        title: Entities
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - light.office_light_223
          - light.sunroom_lights_203
          - entity: light.sunroom_fan_204
            # Override the name to use
            name: LR Fan
        # The markdown card will render markdown text.
#     Card 2
      - type: markdown
        id: c_t2c2
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
#  View 3
  - title: Examples
    id: v_examples
    cards:
#     Card 1
#      - type: alarm-panel
#        title: House Alarm
#        entity: alarm_control_panel.alarm
#        entity: scene.alarm__arm_all_zones
#        states:
#          - arm_home
#          - arm_away
#          - arm_night
#          - armed_custom_bypass
#     Card 2
      - type: entities
        id: c_t3c2
        title: Entities card - simple
        show_header_toggle: true
        entities:
#          - entity: alarm_control_panel.alarm
#            name: Alarm Panel
          - type: divider
          - light.office_light_223
          - switch.office_desk_lamp_27
          - type: divider
          - group.all_lights
          - group.all_locks
          - type: divider
          - type: weblink
            name: Home Assistant
            url: https://www.home-assistant.io/
            icon: mdi:home-assistant
#     Card 3
      - type: entities
        id: c_t3c3
        title: Entities card - service
        show_header_toggle: true
        entities:
          - type: call-service
            icon: mdi:power
            name: Office light
            action_name: Toggle light
            service: light.toggle
            service_data:
              entity_id: light.office_light_223
#     Card 4
#      - type: entity-button
#        id: c_t3c4a
#        entity: switch.office_desk_lamp_27
#      - type: entity-button
#        id: c_t3c4b
#        entity: light.office_light_223
#      - type: entity-button
#        id: c_t3c4c
#        entity: switch.office_fan_224
      - type: entity-button
        id: c_t3c4d
        name: Refresh Geolocation
        tap_action: call-service
        entity: script.refresh_geolocation
        service: script.turn_on
#     Card 5
      - type: entity-filter
        id: c_t3c5
        entities:
          - entity: switch.office_desk_lamp_27
            name: Desk Lamp
          - light.office_light_223
          - switch.office_fan_224
        state_filter:
          - "on"
        show_empty: false
#     Card 6
      - type: gauge
        id: c_t3c6
        title: Memory Use
        unit_of_measurement: '%'
        entity: sensor.memory_use_percent
        severity:
          green: 0
          yellow: 45
          red: 85
#     Card 7
      - type: glance
        id: c_t3c7
        title: Glances
        entities:
#          - entity: binary_sensor.front_door_31
#            name: Front Door
          - binary_sensor.front_door_31
          - binary_sensor.back_door_36
          - binary_sensor.garage_entry_door_39
          - binary_sensor.one_car_gar_sensor_66
          - binary_sensor.two_car_gar_sensor_65
          - light.office_light_223
          - switch.office_desk_lamp_27
#     Card 8
      - type: history-graph
        id: c_t3c8
        title: 'Current Temps Inside/Outside'
        entities:
#          - lock.front_door_bolt_241
#          - binary_sensor.front_door_31
          - sensor.kit_temp_sensor_117
          - sensor.lr_temp_sensor_78
          - sensor.temperature_9
#  View 4
  - title: Examples 2
    id: v_examples2
    cards:
#     Card 1
      - type: horizontal-stack
        id: c_t4c1
        cards:
          - type: picture-entity
            id: c_t4c1a
            image: /local/Arts_Avatar.png
            entity: device_tracker.artsiphone8
          - type: picture-entity
            id: c_t4c1b
            image: /local/Steffs_Avatar.png
            entity: device_tracker.steffsiphone8
#     Card 2
      - type: iframe
        id: c_t4c2
        url: https://icons.wxug.com/data/weather-maps/radar/united-states/saint-petersburg-florida-region-current-radar-animation.gif
        aspect_ratio: 66%
#     Card 3
      - type: map
        id: c_t4c3
        aspect_ratio: 100%
        default_zoom: 11
        entities:
          - device_tracker.artsiphone8
          - zone.home
          - zone.shopping
          - zone.shands
#     Card 4
      - type: picture
        id: c_t4c4
        image: /local/moon_icons/full_moon.png
        navigation_path: /lovelace/v_home
      - type: picture
        image: /local/moon_icons/new_moon.png
        service: switch.toggle
        service_data:
          entity_id: switch.office_desk_lamp_27
#        service: light.toggle
#        service_data:
#          entity_id: light.sunroom_lights_203
#  View 5
  - title: First Floor
    id: v_first_floor
    cards:
#     Card 1
      - type: markdown
        content: >
          ## First Floor
#     Card 2
      - type: horizontal-stack
        id: c_t5c2
        cards:
          - type: entities
            id: c_t5c2a
            title: Inside
            show_header_toggle: true
            entities:
              - switch.kitchen_can_lights_49
              - light.kitchen_pendants_106
              - entity: switch.kitchen_uc_lights_44
                icon: mdi:led-strip
              - entity: light.nook_uc_lights_116
                icon: mdi:led-strip
              - type: divider
              - light.lr_can_lights_62
              - entity: switch.lr_fan_115
                icon: mdi:fan
              - type: divider
              - light.mbr_can_lights_95
              - light.mbr_bath_lights_94
              - entity: switch.mbr_shower_light_92
                icon: mdi:lightbulb
              - entity: switch.mbr_bath_fan_93
                icon: mdi:fan
              - type: divider
              - light.bird_room_1_light_52
              - light.bird_room_2_light_53
          - type: entities
            id: c_t5c2b
            title: Outside
            entities:
              - light.sunroom_lights_203
              - entity: light.sunroom_fan_204
                icon: mdi:fan
              - type: divider
              - switch.pergola_lights_213
              - switch.hot_tub_lights_201
              - entity: switch.outdoor_fountain_124
                icon: mdi:fountain
              - type: divider
              - entity: switch.sun_room_floods_202
                icon: mdi:track-light
              - entity: switch.house_floods_105
                icon: mdi:track-light
              - type: divider
              - switch.porch_light_46
              - switch.garage_lights_48
              - entity: switch.garage_fan_225
                icon: mdi:fan
              - type: divider
              - entity: switch.soffit_east_126
                icon: mdi:power-socket-us
              - entity: switch.soffit_center_123
                icon: mdi:power-socket-us
#     Card 3
      - type: picture-elements
        id: c_t5c3
        image: /local/floorplan/first_floor.png
        elements:
#    KITCHEN
     # Kitchen Can Lights
          - type: state-icon
            tap_action: toggle
            entity: switch.kitchen_can_lights_49
            style:
              top: 50%
              left: 11%
          - type: state-icon
            tap_action: toggle
            entity: switch.kitchen_can_lights_49
            style:
              top: 56%
              left: 11%
          - type: state-icon
            tap_action: toggle
            entity: switch.kitchen_can_lights_49
            style:
              top: 62%
              left: 11%
          - type: state-icon
            tap_action: toggle
            entity: switch.kitchen_can_lights_49
            style:
              top: 50%
              left: 16%
          - type: state-icon
            tap_action: toggle
            entity: switch.kitchen_can_lights_49
            style:
              top: 56%
              left: 16%
     # Kitchen Pendant Lights
          - type: state-icon
            tap_action: toggle
            entity: light.kitchen_pendants_106
            style:
              top: 49%
              left: 24%
          - type: state-icon
            tap_action: toggle
            entity: light.kitchen_pendants_106
            style:
              top: 53%
              left: 24%
          - type: state-icon
            tap_action: toggle
            entity: light.kitchen_pendants_106
            style:
              top: 57%
              left: 24%
#    LIVING ROOM
     # LR Can Lights
          - type: state-icon
            tap_action: toggle
            entity: light.lr_can_lights_62
            style:
              top: 45%
              left: 43%
          - type: state-icon
            tap_action: toggle
            entity: light.lr_can_lights_62
            style:
              top: 45%
              left: 53%
          - type: state-icon
            tap_action: toggle
            entity: light.lr_can_lights_62
            style:
              top: 55%
              left: 43%
          - type: state-icon
            tap_action: toggle
            entity: light.lr_can_lights_62
            style:
              top: 55%
              left: 53%
     # LR Fan
          - type: image
            tap_action: toggle
            entity: switch.lr_fan_115
            state_image:
              "on": /local/icons/fan.png
              "off": /local/icons/fan-off.png
            state_filter:
              "on": brightness(0.8);
              "off": brightness(0.2);
            style:
              top: 50%
              left: 48%
     # Master Bed
          - type: state-icon
            tap_action: toggle
            entity: light.mbr_can_lights_95
            style:
              top: 24%
              left: 72%
          - type: state-icon
            tap_action: toggle
            entity: light.mbr_can_lights_95
            style:
              top: 24%
              left: 89%
          - type: state-icon
            tap_action: toggle
            entity: light.mbr_can_lights_95
            style:
              top: 34%
              left: 72%
          - type: state-icon
            tap_action: toggle
            entity: light.mbr_can_lights_95
            style:
              top: 34%
              left: 89%
     # Master Bath
       # Art Vanity
          - type: state-icon
            tap_action: toggle
            entity: light.mbr_bath_lights_94
            style:
              top: 50%
              left: 92%
       # Steff Vanity
          - type: state-icon
            tap_action: toggle
            entity: light.mbr_bath_lights_94
            style:
              top: 56%
              left: 81%
          - type: state-icon
            tap_action: toggle
            entity: switch.mbr_shower_light_92
            style:
              top: 45%
              left: 92%
          - type: state-icon
            tap_action: toggle
            entity: switch.mbr_bath_fan_93
            style:
              top: 51%
              left: 85%
#    SUN ROOM
     # SR Can Lights
          - type: state-icon
            tap_action: toggle
            entity: light.sunroom_lights_203
            style:
              top: 20%
              left: 50%
     # SR Fan
          - type: image
            tap_action: toggle
            entity: light.sunroom_fan_204
            state_image:
              "on": /local/icons/fan.png
              "off": /local/icons/fan-off.png
            state_filter:
              "on": brightness(0.8);
              "off": brightness(0.2);
            style:
              top: 13%
              left: 50%
          - type: image
            tap_action: toggle
            entity: light.sunroom_fan_204
            state_image:
              "on": /local/icons/fan.png
              "off": /local/icons/fan-off.png
            state_filter:
              "on": brightness(0.8);
              "off": brightness(0.2);
            style:
              top: 27%
              left: 50%
#    BIRD ROOMS
          # Birds Room 1 Lights
          - type: state-icon
            tap_action: toggle
            entity: light.bird_room_1_light_52
            style:
              top: 65%
              left: 82%
          # Birds Room 2 Lights
          - type: state-icon
            tap_action: toggle
            entity: light.bird_room_2_light_53
            style:
              top: 87%
              left: 82%
#    OUTSIDE
     # Pergola Side
          - type: state-icon
            tap_action: toggle
            entity: switch.pergola_lights_213
            style:
              top: 11%
              left: 16%
          - type: state-label
            entity: sensor.dark_sky_apparent_temperature
            style:
              top: 17%
              left: 15%
     # Screen Room Side
          - type: state-icon
            tap_action: toggle
            entity: switch.hot_tub_lights_201
            style:
              top: 12%
              left: 80%
          - type: state-icon
            tap_action: toggle
            entity: switch.outdoor_fountain_124
            style:
              top: 17%
              left: 80%
          - type: service-button
            title: All lights off
            style:
              top: 90%
              left: 30%
            service: homeassistant.turn_off
            service_data:
              entity_id: group.all_lights
     # Front Porch
          - type: state-icon
            tap_action: toggle
            entity: switch.porch_light_46
            style:
              top: 90%
              left: 64%
     # Garage
          - type: state-icon
            tap_action: toggle
            entity: switch.garage_lights_48
            style:
              top: 96%
              left: 57%
          - type: state-icon
            tap_action: toggle
            entity: switch.garage_lights_48
            style:
              top: 96%
              left: 24%
          - type: state-icon
            tap_action: toggle
            entity: switch.garage_lights_48
            style:
              top: 96%
              left: 6%
     # Soffits
          - type: state-icon
            tap_action: toggle
            entity: switch.soffit_east_126
            style:
              top: 98%
              left: 59%
          - type: state-icon
            tap_action: toggle
            entity: switch.soffit_center_123
            style:
              top: 98%
              left: 4%
     # Flood Lights
          - type: state-icon
            tap_action: toggle
            entity: switch.sun_room_floods_202
            style:
              top: 4%
              left: 50%
          - type: state-icon
            tap_action: toggle
            entity: switch.house_floods_105
            style:
              top: 4%
              left: 5%
          - type: state-icon
            tap_action: toggle
            entity: switch.house_floods_105
            style:
              top: 4%
              left: 95%
#          - type: icon
#            icon: mdi:home
#            tap_action: navigate
#            navigation_path: /lovelace/0
#            style:
#              top: 10%
#              left: 10%
#  View 6
  - title: Second Floor
    id: v_second_floor
    cards:
#     Card 1
#      - type: markdown
#        id: c_t6c1
#        content: >
#          ## Second Floor
#     Card 2
      - type: entities
        id: c_t6c2
        title: Second Floor
        show_header_toggle: true
        entities:
          - switch.kitchen_can_lights_49
          - light.kitchen_pendants_106
          - entity: switch.kitchen_uc_lights_44
            icon: mdi:led-strip
          - entity: light.nook_uc_lights_116
            icon: mdi:led-strip
          - type: divider
          - light.lr_can_lights_62
          - entity: switch.lr_fan_115
            icon: mdi:fan
          - type: divider
          - light.mbr_can_lights_95
          - light.mbr_bath_lights_94
#     Card 3
      - type: picture-elements
        id: c_t6c3
        image: /local/floorplan/second_floor.png
        elements:
          - type: state-icon
            tap_action: toggle
            entity: light.lr_can_lights_62
            style:
              top: 47%
              left: 42%
          - type: state-icon
            tap_action: toggle
            entity: switch.kitchen_can_lights_49
            style:
              top: 30%
              left: 15%
          - type: service-button
            title: All lights off
            style:
              top: 90%
              left: 30%
            service: homeassistant.turn_off
            service_data:
              entity_id: group.all_lights
