title: My Home Assistant
excluded_entities:
  - weblink.router
views:
#
#########################################
#  View 1 - HOME
#########################################
#
  - title: Home
    icon: mdi:home
    id: v_home
#    background: radial-gradient(crimson, skyblue)
    cards:
#     Card 2
      - type: alarm-panel
        id: v_home_c2
        title: Alarm Keypad
        entity: alarm_control_panel.ha_alarm
        states:
          - arm_home
          - arm_away
#          - arm_night
#          - disarmed
#          - triggered
#     Card 1
      - type: entity-filter
        id: v_home_c1
        entities:
          - device_tracker.artsiphone8
          - device_tracker.steffsiphone8
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home
#     Card 4
      - type: weather-forecast
        id: c_t1c4
        entity: weather.dark_sky
#
#########################################
#  View 2 - ROOMS
#########################################
#
  - title: Rooms
    id: v_rooms
#    icon: mdi:car
    panel: true
    cards:
    - type: horizontal-stack
      cards:
# COL 1
        - type: vertical-stack
          cards:
            - type: entities
              id: v_rooms_c1
              title: Kitchen
              show_header_toggle: true
              entities:
                - entity: switch.kitchen_can_lights_49
                  icon: mdi:blur-radial
                - entity: light.kitchen_pendants_106
                  icon: mdi:ceiling-light
                - entity: switch.kitchen_uc_lights_44
                  icon: mdi:led-strip
#                - type: section
#                  label: section 2
#                - type: weblink
#                  url: /lovelace/v_rooms
#                  name: name
#                  icon: mdi:link
#
            - type: entities
              id: v_rooms_c2
              title: Living Room
              show_header_toggle: true
              entities:
                - entity: light.lr_can_lights_62
                  icon: mdi:blur-radial
                - entity: switch.lr_fan_115
                  icon: mdi:fan
                - entity: switch.lr_christmas_tree_26
                  icon: mdi:pine-tree
#
            - type: entities
              id: v_rooms_c3
              title: Garage
              show_header_toggle: true
              entities:
                - switch.garage_fan_225
#
# COL 2
        - type: vertical-stack
          cards:
            - type: entities
              id: v_rooms_c4
              title: Sun Room
              show_header_toggle: true
              entities:
                - light.sunroom_lights_203
                - entity: light.sunroom_fan_204
                  icon: mdi:fan
#
            - type: entities
              id: v_rooms_c5
              title: Bird Rooms
              show_header_toggle: true
              entities:
                - light.bird_room_1_light_52
                - light.bird_room_2_light_53
#
            - type: entities
              id: v_rooms_c6
              title: Bonus Room
              show_header_toggle: true
              entities:
                - entity: switch.office_desk_lamp_27
                  icon: mdi:desk-lamp
                - light.office_light_223
                - entity: switch.office_fan_224
                  icon: mdi:fan
#
# COL 3
        - type: vertical-stack
          cards:
            - type: entities
              id: v_rooms_c7
              title: Master Bed/Bath
              show_header_toggle: true
              entities:
                - entity: light.mbr_can_lights_95
                  icon: mdi:blur-radial
                - light.mbr_bath_lights_94
                - entity: switch.mbr_shower_light_92
                  icon: mdi:blur-radial
                - entity: switch.mbr_bath_fan_93
                  icon: mdi:fan
#
            - type: entities
              id: v_rooms_c8
              title: Locks
              show_header_toggle: true
              entities:
                - lock.front_door_bolt_241
                - lock.back_door_lock_61
                - entity: lock.garage_controller_1_55
                  icon: mdi:garage
                - entity: lock.garage_controller_2_54
                  icon: mdi:garage
# COL 4
        - type: vertical-stack
          cards:
            - type: entities
              id: v_rooms_c9
              title: Outside
              show_header_toggle: true
              entities:
                - entity: switch.pergola_lights_213
                  icon: mdi:led-on
                - entity: switch.hot_tub_lights_201
                  icon: mdi:led-on
                - entity: switch.sun_room_floods_202
                  icon: mdi:track-light
                - entity: switch.house_floods_105
                  icon: mdi:track-light
                - entity: switch.garage_lights_48
                  icon: mdi:wall-sconce
                - entity: switch.holiday_lights_222
                  icon: mdi:led-on
                - entity: switch.outdoor_fountain_124
                  icon: mdi:fountain
                - entity: switch.porch_light_46
                  icon: mdi:ceiling-light
                - entity: switch.soffit_east_126
                  icon: mdi:power-socket-us
                - entity: switch.soffit_center_123
                  icon: mdi:power-socket-us
#
#########################################
#  View 3 CONFIGURATION
#########################################
#
  - title: Configuration
    id: v_config
#    icon: mdi:car
#    panel: true
    cards:
      - type: entities
        id: v_config_c_1
        title: Alarm System
        show_header_toggle: false
        entities:
          - entity: input_boolean.alarm_auto
            icon: mdi:shield
          - entity: input_boolean.alarm_tripped
            icon: mdi:alarm-light
          - entity: input_boolean.alarm_silence
            icon: mdi:bell-off
          - entity: input_boolean.alarm_panic_mode
            icon: mdi:led-on
          - type: divider
          - entity: input_boolean.enable_persistant_notifications
            icon: mdi:message
          - entity: input_boolean.enable_push_notifications
            icon: mdi:message
          - entity: input_boolean.enable_prowl_notifications
            icon: mdi:message
#
      - type: entities
        id: v_config_c_2
        title: Users
        show_header_toggle: false
        entities:
          - entity: input_boolean.art_home
            icon: mdi:home-account
#          - entity: input_boolean.art_away
#            icon: mdi:home-outline
#          - entity: input_boolean.art_working
#            icon: mdi:hospital-building
          - entity: input_boolean.steff_home
            icon: mdi:home-account
#          - entity: input_boolean.steff_away
#            icon: mdi:home-outline
#          - entity: input_boolean.steff_shopping
#            icon: mdi:cart
          - type: divider
          - entity: input_boolean.everyone_home
            icon: mdi:account-supervisor-circle
          - entity: input_boolean.someone_home
            icon: mdi:account-circle
          - entity: input_boolean.no_one_home
            icon: mdi:account-circle-outline
#
#########################################
#  View 4 - HVAC
#########################################
#
  - title: HVAC
    id: v_hvac
#    icon: mdi:car
    panel: true
    cards:
    - type: horizontal-stack
      cards:
# COL 1
        - type: vertical-stack
          cards:
          - type: thermostat
            id: v_hvac_c1_1
            title: Downstairs
            show_header_toggle: false
            entity: climate.tstat_1_144
          - type: horizontal-stack
            id: v_hvac_c1_2
            cards:
              - type: sensor
                entity: sensor.kit_temp_sensor_117
                name: Kitchen
                height: 75
                detail: 6
                hours_to_show: 12
              - type: sensor
                entity: sensor.lr_temp_sensor_78
                name: Living Room
                height: 75
                detail: 6
                hours_to_show: 12
                line_color: red
# COL 2
        - type: vertical-stack
          cards:
          - type: history-graph
            id: v_hvac_c2_1
            title: 'Temperature Graph'
            refresh_interval: 900
            hours_to_show: 12
            entities:
              - entity: sensor.temperature_9
                name: Outside Temp
              - entity: sensor.kit_temp_sensor_117
                name: Inside Temp
          - type: picture
            id: v_hvac_c2_2
            image: https://cdn.tegna-media.com/wtlv/weather/7Day_forecast.jpg
#
# COL 3
        - type: vertical-stack
          cards:
            - type: thermostat
              id: v_hvac_c3_1
              title: Upstairs
              show_header_toggle: false
              entity: climate.tstat_2_145
#            - type: horizontal-stack
#              id: v_hvac_c3_2
#              cards:
#                - type: entity-button
#                  entity: switch.lr_fan_115
#                  icon: mdi:fan
#                  tap_action: toggle
#                  hold_action: more-info
#                - type: entity-button
#                  entity: light.sunroom_fan_204
#                  icon: mdi:fan
#                  tap_action: toggle
#                  hold_action: more-info
#                - type: entity-button
#                  entity: switch.office_fan_224
#                  icon: mdi:fan
#                  tap_action: toggle
#                  hold_action: more-info
#                - type: entity-button
#                  entity: switch.garage_fan_225
#                  icon: mdi:fan
#                  tap_action: toggle
#                  hold_action: more-info
            - type: glance
              id: v_hvac_c3_3
              title: Temp & Humidity Sensor Readings
              entities:
               - sensor.kit_temp_sensor_117
               - sensor.kit_humidity_sensor_119
               - sensor.lr_temp_sensor_78
               - sensor.lr_humidity_sensor_80
