# Create a header by using `panel: true` with nested stack cards
title: Rooms
id: v_rooms
views:
# COL 1
  - type: vertical-stack
    cards:
      - type: entities
        title: Kitchen
        show_header_toggle: true
        entities:
          - entity: switch.kitchen_can_lights_49
            icon: mdi:blur-radial
          - entity: light.kitchen_pendants_106
            icon: mdi:ceiling-light
          - entity: switch.kitchen_uc_lights_44
            icon: mdi:led-strip
#                      - type: section
#                        label: section 2
#                      - type: weblink
#                        url: /lovelace/v_rooms
#                        name: name
#                        icon: mdi:link
#
      - type: entities
        title: Living Room
        show_header_toggle: true
        entities:
          - entity: light.lr_can_lights_62
            icon: mdi:blur-radial
          - entity: switch.lr_fan_115
            icon: mdi:fan
          - entity: switch.lr_christmas_tree_26
            icon: mdi:pine-tree
#
      - type: entities
        title: Garage
        show_header_toggle: true
        entities:
          - switch.garage_fan_225
#
# COL 2
  - type: vertical-stack
    cards:
      - type: entities
        title: Sun Room
        show_header_toggle: true
        entities:
          - light.sunroom_lights_203
          - entity: light.sunroom_fan_204
            icon: mdi:fan
#
      - type: entities
        title: Bird Rooms
        show_header_toggle: true
        entities:
          - light.bird_room_1_light_52
          - light.bird_room_2_light_53
#
      - type: entities
        title: Bonus Room
        show_header_toggle: true
        entities:
          - switch.office_desk_lamp_27
          - light.office_light_223	
          - switch.office_fan_224	
#
# COL 3
  - type: vertical-stack
    cards:
      - type: entities
        title: Master Bed/Bath
        show_header_toggle: true
        entities:
          - light.mbr_can_lights_95
          - light.mbr_bath_lights_94
          - switch.mbr_shower_light_92
          - switch.mbr_bath_fan_93
#
      - type: entities
        title: Outside
        show_header_toggle: true
        entities:
          - switch.sun_room_floods_202
          - switch.garage_lights_48
          - switch.garage_lights_48
          - switch.garage_lights_48
#
# COL 4
  - type: vertical-stack
    cards:
      - type: entities
        title: Locks
        show_header_toggle: true
        entities:
          - lock.garage_controller_1_55
          - lock.garage_controller_2_54
          - lock.garage_controller_1_55
          - lock.garage_controller_2_54
