homeassistant:
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
##    - type: legacy_api_password
##      api_password: !secret api_password
    - type: trusted_networks
      trusted_networks:
      - !secret trusted_network1
      - !secret trusted_network2
      - !secret external_ip
#  ---------------------------------------------------------------------------
# Enables Breaking Changes Sensor (>0.96)
breaking_changes:
#  ---------------------------------------------------------------------------
# Enables configuration UI
config:
#  ---------------------------------------------------------------------------
# configures a default set of integrations for Home Assistant to load
default_config:
# https://www.home-assistant.io/integrations/default_config/
#  ---------------------------------------------------------------------------
# Discover and automatically configure zeroconf/mDNS and uPnP devices
#discovery:
#  ignore:
#    - apple_tv
#    - roku
#    - sonos
#  ---------------------------------------------------------------------------
# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes
#  ---------------------------------------------------------------------------
# Enables support for IOS
#ios:
# see Include section below!
#  ---------------------------------------------------------------------------
# Enables support for tracking state changes over time
logbook:
#  ---------------------------------------------------------------------------
logger:
# https://www.home-assistant.io/components/logger/
  default: info
#  logs:
#    homeassistant.components.device_tracker: critical
#    homeassistant.components.camera: critical
#  ---------------------------------------------------------------------------
# Lovelace configuration via YAML
lovelace:
  mode: yaml
#  ---------------------------------------------------------------------------
# Enables a map showing the location of tracked devices
map:
#  ---------------------------------------------------------------------------
# Allows Home Assistant mobile apps to easily integrate with Home Assistant.
mobile_app:
#  ---------------------------------------------------------------------------
# Enables lovelace momentary switches
momentary:
#  ---------------------------------------------------------------------------
# Enable Person component
person:
#  ---------------------------------------------------------------------------
# Enable Python scripts
#python_script:
#  ---------------------------------------------------------------------------
# Track the sun
sun:
#  ---------------------------------------------------------------------------
# System Health component
system_health:
#  ---------------------------------------------------------------------------
# Text to speech - Required for Sonos Say??
tts:
  - platform: google_translate
    service_name: google_say
#  ---------------------------------------------------------------------------
# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true
#  ---------------------------------------------------------------------------
#
# Included files
alarm_control_panel: !include includes/alarm_cp.yaml
automation: !include_dir_merge_list automations
binary_sensor: !include includes/binary_sensors.yaml
#camera: !include_dir_merge_list cameras
device_tracker: !include includes/device_trackers.yaml
fan: !include includes/fans.yaml
group: !include_dir_merge_named groups
history: !include includes/history_cfgs.yaml
##ios: !include includes/ios_cfg.yaml
###http: !include includes/http_cfgs.yaml
input_boolean: !include includes/input_booleans.yaml
input_datetime: !include includes/input_datetimes.yaml
input_number: !include includes/input_numbers.yaml
input_select: !include includes/input_selects.yaml
input_text: !include includes/input_texts.yaml
light: !include includes/lights.yaml
media_player: !include includes/media_players.yaml
#mqtt: !include includes/mqtt_cfgs.yaml
notify: !include_dir_merge_list notify
proximity: !include includes/proximity.yaml
recorder: !include includes/recorders.yaml
scene: !include_dir_list scenes
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
switch: !include includes/switches.yaml
weblink: !include includes/weblinks.yaml
zone: !include includes/zones.yaml
#
# ******************************************************************************
#    Additional Components - alphabetically listed
#*******************************************************************************
#  ---------------
# Alexa Media Player
# https://github.com/keatontaylor/custom_components/wiki/Configuration
# https://github.com/keatontaylor/custom_components/tree/master/alexa_media
alexa_media:
  accounts:
    - email: !secret alexa_email
      password: !secret alexa_pw
      url: amazon.com
#
#  ---------------------------------------------------------------------------
# Enable Home Assistant Community Store
hacs:
  token: !secret githubtoken1
  appdaemon: True
  # Enable tracking of AppDaemon apps.
  #python_script: True
  # Enable tracking of python scripts.
  #theme: True
  # Enable tracking of themes.
#
#  ---------------------------------------------------------------------------
# Own Tracks
owntracks:
  max_gps_accuracy: 50
  events_only: false
#  waypoints: true
#
#  ---------------------------------------------------------------------------
# Rachio Irrigation Control
#rachio:
#  api_key: !secret rachio_api_key
#
#  ---------------------------------------------------------------------------
# Roku TV
roku:
  host: !secret roku_url
#
#  ---------------------------------------------------------------------------
# Sleep IQ Bed
sleepiq:
  username: !secret sleepiq_un
  password: !secret sleepiq_pw
#
#  ---------------------------------------------------------------------------
# Vera Setup
vera:
  vera_controller_url: !secret vera_url
  # Optional to exclude devices - this is a list of vera device ids
  exclude: [ 7, 13, 14, 47, 57, 61, 86, 87, 109, 110, 133, 134, 135, 136, 140, 147, 155, 172, 174, 176, 178, 180, 182, 189, 205]
  # Optional to import switches as lights - this is a list of vera device ids
  lights: [25, 26, 27, 29, 40, 44, 46, 48, 49, 52, 53, 62, 92, 93, 94, 95, 105, 106, 115, 123, 124, 126, 201, 202, 203, 213, 222, 224, 225, 242, 278]
#  204 Sunroom Fan Controller
#  ---------------------------------------------------------------------------
# Weather - Dark Sky Weather
# See also [sensors/dark_sky.yaml]
weather:
  - platform: darksky
    mode: daily
    api_key: !secret darksky_api_key
#  - platform: nws
#    api_key: !secret nws_api
#    mode: daynight
#    station: KJAX
#  ---------------------------------------------------------------------------
#

