#########################
#    Command Line       #
#########################
- platform: command_line
  name: Days In Current Month
  command: cal $(date +"%m %Y") | awk 'NF {DAYS = $NF}; END {print DAYS}'
  scan_interval: 3600
#
#- platform: command_line
#  name: Birthday Countdown Art
#  unit_of_measurement: days
#  scan_interval: 3600
#  command: "BDAY=`date -d 1959-4-16 +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; DAYS=$(($BDAY - $TODAY)); echo $DAYS"
#
#- platform: command_line
#  name: Birthday Countdown Steff
#  unit_of_measurement: days
#  scan_interval: 3600
#  command: "BDAY=`date -d 1953-9-20 +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; DAYS=$(($BDAY - $TODAY)); echo $DAYS"
#
# ------------------------
#- platform: command_line
#  name: todays_events
#  command: 'cat www/holidays.json'
# -- OR --
#- platform: file
#  name: todays_events
#  file_path: /config/www/holidays.json
# ------------------------
#- platform: command_line
#  name: todays_events
#  #command: 'cat /Users/artdavis/.homeassistant/www/holidays.json'
#  command: 'cat /Users/artdavis/.homeassistant/holidays.json'
#  #command: 'cat /config/holidays.json'
#  value_template: >
#    {% set today = now().month  ~ '/' ~ now().day  %}
#    {% set holiday =  value_json.MAJOR_US.static[ today ] %}
#    {% if holiday | trim == "" %}
#      {% set today = now().month  ~ '/' ~ now().day ~ '/' ~ now().year %}
#      {% set holiday =  value_json.MAJOR_US.dynamic[ today ] %}
#    {% endif %}
#    {{ holiday }}
#  scan_interval: 14400
