#########################
#    Command Line       #
#########################
- platform: command_line
  name: Days In Current Month
  command: cal $(date +"%m %Y") | awk 'NF {DAYS = $NF}; END {print DAYS}'
  scan_interval: 3600
#
# ------------------------
# FULL PATH: /Users/artdavis/.homeassistant/www/holidays.json
# PROJECT PATH: www/holidays.json
# ------------------------
#- platform: command_line
#  name: todays_events
#  command: 'cat www/holidays.json'
# -- OR --
#- platform: file
#  name: todays_events
#  file_path: /config/www/holidays.json
# ------------------------
#- platform: command_line
#  name: todays_events
#  #command: 'cat /Users/artdavis/.homeassistant/www/holidays.json'
#  command: 'cat /Users/artdavis/.homeassistant/holidays.json'
#  #command: 'cat /config/holidays.json'
#  value_template: >
#    {% set today = now().month  ~ '/' ~ now().day  %}
#    {% set holiday =  value_json.MAJOR_US.static[ today ] %}
#    {% if holiday | trim == "" %}
#      {% set today = now().month  ~ '/' ~ now().day ~ '/' ~ now().year %}
#      {% set holiday =  value_json.MAJOR_US.dynamic[ today ] %}
#    {% endif %}
#    {{ holiday }}
#  scan_interval: 14400
#  *******************************************************************************
- platform: rest
  #resource: https://github.com/kartcon/.homeassistant/blob/master/holidays.json
  resource: https://raw.githubusercontent.com/kartcon/.homeassistant/master/holidays.json?token=ACTWADCFBQS63NUWX7C2IHK5MCDG4
  name: events_art1
  scan_interval: 14400
  value_template: >
    {% set today = now().month  ~ '/' ~ now().day  %}
    {% set holiday =  value_json.MAJOR_US.static[ today ] %}
    {% if holiday | trim == "" %}
      {% set today = now().month  ~ '/' ~ now().day ~ '/' ~ now().year %}
      {% set holiday =  value_json.MAJOR_US.dynamic[ today ] %}
    {% endif %}
    {{ holiday }}
#
#  *******************************************************************************
- platform: rest
  #resource: https://github.com/kartcon/.homeassistant/blob/master/holidays.json
  resource: https://raw.githubusercontent.com/kartcon/.homeassistant/master/holidays.json
  name: events_art2
  scan_interval: 14400
  value_template: >
    {% set today = now().month  ~ '/' ~ now().day  %}
    {% set holiday =  value_json.MAJOR_US.static[ today ] %}
    {% if holiday | trim == "" %}
      {% set today = now().month  ~ '/' ~ now().day ~ '/' ~ now().year %}
      {% set holiday =  value_json.MAJOR_US.dynamic[ today ] %}
    {% endif %}
    {{ holiday }}
#
#  *******************************************************************************
- platform: rest
  resource: https://raw.githubusercontent.com/SilvrrGIT/HomeAssistant/master/www/days.json
  name: events_silvrr
  scan_interval: 14400
  value_template: >
    {% set today = now().month  ~ '/' ~ now().day  %}
    {% set holiday =  value_json.MAJOR_US.static[ today ] %}
    {% if holiday | trim == "" %}
      {% set today = now().month  ~ '/' ~ now().day ~ '/' ~ now().year %}
      {% set holiday =  value_json.MAJOR_US.dynamic[ today ] %}
    {% endif %}
    {{ holiday }}
#
#  *******************************************************************************
- platform: rest
  resource: https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/json_data/holidays.json
  name: events_ccostan
  scan_interval: 14400
  value_template: >
    {% set today = now().month  ~ '/' ~ now().day  %}
    {% set holiday =  value_json.MAJOR_US.static[ today ] %}
    {% if holiday | trim == "" %}
      {% set today = now().month  ~ '/' ~ now().day ~ '/' ~ now().year %}
      {% set holiday =  value_json.MAJOR_US.dynamic[ today ] %}
    {% endif %}
    {{ holiday }}
