#############################################################
#              Geo-Location Templates                       #
#############################################################
#
############################
#         Badges           #
############################
#
- platform: template
  sensors:
    #--- Art/Steff location badge --------------------
    art_badge:
      value_template: >-
        {% if states("device_tracker.arts_iphone_8") %}
          {% if states("device_tracker.arts_iphone_8") != "not_home" %}
            {{ states("device_tracker.arts_iphone_8") | title }}
          {% elif states("proximity.art_to_home") %}
            {{ states("proximity.art_to_home") }} mi
          {% else %}
            Waiting
          {% endif %}
        {% endif %}
      friendly_name: 'Arts Avatar'
      entity_picture_template: /local/avatars/Arts_Avatar.png
#
    steff_badge:
      value_template: >-
        {% if states("device_tracker.steffs_iphone_8") %}
          {% if states("device_tracker.steffs_iphone_8") != "not_home" %}
            {{ states("device_tracker.steffs_iphone_8") | title }}
          {% elif states("proximity.steff_to_home") %}
            {{ states("proximity.steff_to_home") }} mi
          {% else %}
            Waiting
          {% endif %}
        {% endif %}
      friendly_name: 'Steffs Avatar'
      entity_picture_template: /local/avatars/Steffs_Avatar.png
#
############################
# Arts Direction of Travel #
############################
- platform: template
  sensors:
    art_travel_direction:
      value_template: '{{state_attr("proximity.art_to_home","dir_of_travel")}}'
      friendly_name: "Art's Travel Direction"
#
############################
#Steffs Direction of Travel#
############################
- platform: template
  sensors:
    steff_travel_direction:
      value_template: '{{state_attr("proximity.steff_to_home","dir_of_travel")}}'
      friendly_name: "Steff's Travel Direction"
#
############################
#    Presence Confidence   #
############################
- platform: template
  sensors:
    presence_confidence_art:
      value_template: "{{ ((states.binary_sensor.art_presence.attributes.probability)*100) }}"
      friendly_name: "Presence Confidence Art"
      unit_of_measurement: '%'
    presence_confidence_steff:
      value_template: "{{ ((states.binary_sensor.steff_presence.attributes.probability)*100) }}"
      friendly_name: "Presence Confidence Steff"
      unit_of_measurement: '%'
#
