#########################
#    REST Sensors       #
#########################
#  *******************************************************************************
#  Get event data for Birthday/Holiday schedule from GitHub repository
#  *******************************************************************************
- platform: rest
  resource: https://raw.githubusercontent.com/kartcon/Home-Assistant-Public/master/json_files/holidays.json
  name: todays_events
  scan_interval: 21600
  value_template: >
    {% set today = now().month  ~ '/' ~ now().day  %}
    {% set holiday =  value_json.MAJOR_US.static[ today ] %}
    {% if holiday | trim == "" %}
      {% set today = now().month  ~ '/' ~ now().day ~ '/' ~ now().year %}
      {% set holiday =  value_json.MAJOR_US.dynamic[ today ] %}
    {% endif %}
    {{ holiday }}
#
#  *******************************************************************************
#  Get event data for Bird Weight schedule from GitHub repository
#  *******************************************************************************
- platform: rest
  resource: https://raw.githubusercontent.com/kartcon/Home-Assistant-Public/master/json_files/weigh_birds.json
  name: weigh_birds
  scan_interval: 21600
  value_template: >
    {% set today = now().month  ~ '/' ~ now().day ~ '/' ~ now().year %}
    {% set weighday =  value_json.WEIGH_DAY.dynamic[ today ] %}
    {{ weighday }}
#
#  *******************************************************************************
#  US Weather Service Emergency Data
#  https://community.home-assistant.io/t/severe-weather-alerts-from-the-us-national-weather-service/71853
#  *******************************************************************************
- platform: rest
  resource: https://api.weather.gov/alerts/active?zone=FLZ125
  name: NWS Alert Event
  value_template: >
    {% if value_json.features[0] is defined %}
      {{ value_json['features'][0]['properties'].event }}
    {% else %}
      None
    {% endif %}
  json_attributes:
    - features
  headers:
    User-Agent: Homeassistant
    Accept: application/geo+json
  scan_interval: 3600
#
#  *******************************************************************************
#  US Weather Service Emergency Data
#  https://community.home-assistant.io/t/severe-weather-alerts-from-the-us-national-weather-service/71853
#  *******************************************************************************
- platform: rest
  resource: https://api.weather.gov/alerts/active/count
  name: NWS Alert Count
  value_template: >
    {% if value_json.zones.FLZ125 is defined %}
      {{ value_json.zones.FLZ125 }}
    {% else %}
      0
    {% endif %}
  headers:
    User-Agent: Homeassistant
    Accept: application/ld+json
  scan_interval: 3600
#  *******************************************************************************
#  See also: sensors/environmental.yaml - Weather.gov Alerts
#  *******************************************************************************
#    {% elif value_json.zones.FLC031 is defined %}
#      {{ value_json.zones.FLC031 }}
#
