#########################
#    HA User            #
#########################
# platform: template
#  sensors:
#    logged_user:
#      value_template: "{{ user.name }}"
#      friendly_name: "Logged User"
#
#########################
#    HA Uptime          #
#########################
- platform: uptime
  name: Uptime
  unit_of_measurement: hours
#
#########################
#    HA Version         #
#########################
- platform: version
  name: version_current
- platform: version
  name: version_available
  source: hassio
#  branch: stable
#
#########################
#  External IP Address  #
#########################
- platform: rest
  resource: https://api.ipify.org/?format=json
  #resource: http://ip.jsontest.com
  name: external_ip
  value_template: '{{ value_json.ip }}'
  scan_interval: 14400
#
#########################
#    System Monitor     #
#########################
- platform: systemmonitor
  resources:
#    - type: ipv4_address
#      arg: en0
    - type: memory_use
    - type: memory_free
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: last_boot
    #########################
    #  LAN IP Address  #
    #########################
    - type: ipv4_address
      arg: en0
#      friendly_name: LAN IP
    #########################
    #  WiFi IP Address  #
    #########################
    - type: ipv4_address
      arg: en1
#      friendly_name: WiFi IP
#
#########################
#    File Size      #
#########################
#https://www.home-assistant.io/components/sensor.filesize/
#- platform: filesize
#  file_paths:
#    - /config/home-assistant_v2.db
#    - /config/home-assistant.log
#
#
#====================================
#=== Home Assistant Component counts
#====================================
- platform: template
  sensors:
  #----- Count Automations
    automation_count:
      entity_id: []
      friendly_name: 'Number of Automations'
      value_template: "{{ states.automation | list | length }}"
  #----- Count Binary Sensors
    binary_sensor_count:
      entity_id: []
      friendly_name: 'Number of Binary Sensors'
      value_template: "{{ states.binary_sensor| list | length }}"
  #----- Count Cameras
    camera_count:
      entity_id: []
      friendly_name: 'Number of Cameras'
      value_template: "{{ states.camera | list | length }}"
  #----- Count Climate Sensors
    climate_count:
      entity_id: []
      friendly_name: 'Number of Climate Sensors'
      value_template: "{{ states.climate | list | length }}"
  #----- Count Device Trackers
    device_tracker_count:
      entity_id: []
      friendly_name: 'Number of Device Trackers'
      value_template: "{{ states.device_tracker | list | length }}"
  #----- Input Booleans
    input_boolean_count:
      entity_id: []
      friendly_name: 'Number of Input Booleans'
      value_template: "{{ states.input_boolean | list | length }}"
  #----- Input Date Times
    input_date_count:
      entity_id: []
      friendly_name: 'Number of Input Dates'
      value_template: "{{ states.input_datetime | list | length }}"
  #----- Input Numbers
    input_number_count:
      entity_id: []
      friendly_name: 'Number of Input Numbers'
      value_template: "{{ states.input_number | list | length }}"
  #----- Input Selects
    input_select_count:
      entity_id: []
      friendly_name: 'Number of Input Selects'
      value_template: "{{ states.input_select | list | length }}"
  #----- Input Texts
    input_text_count:
      entity_id: []
      friendly_name: 'Number of Input Texts'
      value_template: "{{ states.input_text | list | length }}"
  #----- Count Lights
    lights_count:
      entity_id: []
      friendly_name: 'Number of Lights'
      value_template: "{{ states.light | list | length }}"
  #----- Count Locks
    locks_count:
      entity_id: []
      friendly_name: 'Number of Locks'
      value_template: "{{ states.lock | list | length }}"
  #----- Count Media Players
    media_player_count:
      entity_id: []
      friendly_name: 'Number of Media Players'
      value_template: "{{ states.media_player | list | length }}"
  #----- Count Persons
    persons_count:
      entity_id: []
      friendly_name: 'Number of Persons'
      value_template: "{{ states.person | list | length }}"
  #----- Count Scripts
    script_count:
      entity_id: []
      friendly_name: 'Number of Scripts'
      value_template: "{{ states.script| list | length }}"
  #----- Count Sensors
    sensor_count:
      entity_id: []
      friendly_name: 'Number of Sensors'
      value_template: "{{ states.sensor | list | length }}"
  #----- Count Switches
    switch_count:
      entity_id: []
      friendly_name: 'Number of Switches'
      value_template: "{{ states.switch | list | length }}"
  #----- Count Zones
    zone_count:
      entity_id: []
      friendly_name: 'Number of Zones'
      value_template: "{{ states.zone | list | length }}"
#
