#########################
#    HA Uptime          #
#########################
- platform: uptime
  name: Uptime
  unit_of_measurement: hours
#
#########################
#    HA Version         #
#########################
- platform: version
  name: version_current
- platform: version
  name: version_available
  source: hassio
#  branch: stable
#
#########################
#  External IP Address  #
#########################
- platform: rest
  resource: https://api.ipify.org/?format=json
  #resource: http://ip.jsontest.com
  name: external_ip
  value_template: '{{ value_json.ip }}'
  scan_interval: 14400
#
#########################
#    Speed Test         #
#########################
# https://www.home-assistant.io/components/speedtestdotnet/
- speedtestdotnet:
  scan_interval:
    hours: 6
    minutes: 0
  monitored_conditions:
    - ping
    - download
    - upload
#
#########################
#    System Monitor     #
#########################
- platform: systemmonitor
  resources:
#    - type: ipv4_address
#      arg: en0
    - type: memory_use
    - type: memory_free
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: last_boot
    #########################
    #  LAN IP Address  #
    #########################
    - type: ipv4_address
      arg: en0
#      friendly_name: LAN IP
    #########################
    #  WiFi IP Address  #
    #########################
    - type: ipv4_address
      arg: en1
#      friendly_name: WiFi IP
#
#########################
#    Time and Date      #
#########################
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
#
#########################
#    File Size      #
#########################
#https://www.home-assistant.io/components/sensor.filesize/
#- platform: filesize
#  file_paths:
#    - /config/home-assistant_v2.db
#    - /config/home-assistant.log
#
#
#Thanks to @ccostan for the code here.  Some Intresting HA stats
- platform: template
  sensors:
    automation_count:
      entity_id: []
      friendly_name: 'Number of Automations'
      value_template: >
        {%- set domains = ['automation'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    binary_sensor_count:
      entity_id: []
      friendly_name: 'Number of Binary Sensors'
      value_template: >
        {%- set domains = ['binary_sensor'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    camera_count:
      entity_id: []
      friendly_name: 'Number of Cameras'
      value_template: >
        {%- set domains = ['camera'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    climate_count:
      entity_id: []
      friendly_name: 'Number of Climate Sensors'
      value_template: >
        {%- set domains = ['climate'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    input_boolean_count:
      entity_id: []
      friendly_name: 'Number of Input Booleans'
      value_template: >
        {%- set domains = ['input_boolean'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    input_date_count:
      entity_id: []
      friendly_name: 'Number of Input Dates'
      value_template: >
        {%- set domains = ['input_datetime'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    input_number_count:
      entity_id: []
      friendly_name: 'Number of Input Numbers'
      value_template: >
        {%- set domains = ['input_number'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    input_select_count:
      entity_id: []
      friendly_name: 'Number of Input Selects'
      value_template: >
        {%- set domains = ['input_select'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    lights_count:
      entity_id: []
      friendly_name: 'Number of Lights'
      value_template: >
        {%- set domains = ['light'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    locks_count:
      entity_id: []
      friendly_name: 'Number of Locks'
      value_template: >
        {%- set domains = ['lock'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    media_player_count:
      entity_id: []
      friendly_name: 'Number of Media Players'
      value_template: >
        {%- set domains = ['media_player'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    persons_count:
      entity_id: []
      friendly_name: 'Number of Persons'
      value_template: >
        {%- set domains = ['person'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    script_count:
      entity_id: []
      friendly_name: 'Number of Scripts'
      value_template: >
        {%- set domains = ['script'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    sensor_count:
      entity_id: []
      friendly_name: 'Number of Sensors'
      value_template: >
        {%- set domains = ['sensor'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    switch_count:
      entity_id: []
      friendly_name: 'Number of Switches'
      value_template: >
        {%- set domains = ['switch'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    tracker_count:
      entity_id: []
      friendly_name: 'Number of Device Trackers'
      value_template: >
        {%- set domains = ['device_tracker'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    zone_count:
      entity_id: []
      friendly_name: 'Number of Zones'
      value_template: >
        {%- set domains = ['zone'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
#
#  ----------------------------------------------
#  scene(0), proximity(2), updater(1), weather(1) & weblinbk(2)
#  unaccounted for in above counts.
#
