#########################
#     OwnTracks         #
#########################
#
- platform: template
  sensors:
    owntracks_config:
      value_template: "{{(states('input_text.owntracks_config'))}}"
      friendly_name: "OT Encryption Key"
#
- platform: template
  sensors:
    external_url:
      value_template: "XXXX://{{states('sensor.external_ip')}}:8123"
      friendly_name: "External URL"
#      unit_of_measurement: '%'
# states('sensor.external_ip')
- platform: template
  sensors:
    briefing_recipient:
      value_template: >-
        {% if states.input_boolean.someone_home.state == 'on' %}
          {% if (states.input_boolean.steff_home.state == 'on') %}
            Steff
          {% else %}
            Art
          {% endif %}
        {% endif %}
        {% if (states.input_boolean.everyone_home.state == 'on') %}
          Everyone
        {% endif %}
#
