#########################
#   Waze Travel Time    #
#########################
# Travel Times
- platform: waze_travel_time
  name: Art To Home
  origin: person.art
  destination: zone.home
  region: 'US'
  realtime: false
  scan_interval: 3600
- platform: waze_travel_time
  name: Steff To Home
  origin: person.steff
  destination: zone.home
  region: 'US'
  realtime: false
  scan_interval: 3600
#- platform: waze_travel_time
#  name: To Baptist
#  origin: person.art
#  destination: zone.baptist
#  region: 'US'
#  realtime: false
#  scan_interval: 86400
#- platform: waze_travel_time
#  name: To Flagler
#  origin: person.art
#  destination: zone.flagler
#  region: 'US'
#  realtime: false
#  scan_interval: 86400
#- platform: waze_travel_time
#  name: To Mayo Clinic
#  origin: person.art
#  destination: zone.mayo
#  region: 'US'
#  realtime: false
#  scan_interval: 86400
#- platform: waze_travel_time
#  name: To Memorial
#  origin: person.art
#  destination: zone.memorial
#  region: 'US'
#  realtime: false
#  scan_interval: 86400
#- platform: waze_travel_time
#  name: To Monroe
#  origin: person.art
#  destination: zone.monroe
#  region: 'US'
#  realtime: false
#  scan_interval: 86400
#- platform: waze_travel_time
#  name: To Phoebe Ga
#  origin: person.art
#  destination: zone.phoebe
#  region: 'US'
#  realtime: false
#  scan_interval: 86400
#- platform: waze_travel_time
#  name: To Shands Jax
#  origin: person.art
#  destination: zone.shands_jax
#  region: 'US'
#  realtime: false
#  scan_interval: 86400
#- platform: waze_travel_time
#  name: To Shands North
#  origin: person.art
#  destination: zone.shands_north
#  region: 'US'
#  realtime: false
#  scan_interval: 86400
#- platform: waze_travel_time
#  name: To St Vincents
#  origin: person.art
#  destination: zone.st_vincents
#  region: 'US'
#  realtime: false
#  scan_interval: 86400
#- platform: waze_travel_time
#  name: To Tallahassee
#  origin: person.art
#  destination: zone.tallahassee
#  region: 'US'
#  realtime: false
#  scan_interval: 86400
#- platform: waze_travel_time
#  name: To Mom & Dad
#  origin: person.art
#  destination: zone.mom_dad
#  region: 'US'
#  realtime: false
#  scan_interval: 86400
#
