#########################
#  Alarm Control Panel  #
#########################
#
- platform: manual
  name: HA Alarm
  code: !secret alarm_code
#  pending_time: 30
#  delay_time: 20
#  trigger_time: 4
  disarmed:
    trigger_time: 0
  armed_home:
    pending_time: 15
    delay_time: 15
    trigger_time: 30
  armed_night:
    pending_time: 10
    delay_time: 10
    trigger_time: 15
  armed_away:
    pending_time: 10
    delay_time: 10
    trigger_time: 30
#