#########################
#    Ping Sensors       #
#########################
- platform: ping
  name: Ping Cloud Key
  host: !secret cloud_key_url
  scan_interval: 300
#
- platform: ping
  name: Ping Xfinity Router
  host: !secret xfinity_router_url
  scan_interval: 300
#
- platform: ping
  name: Ping Vera Secure
  host: !secret vera_secure_url
  scan_interval: 300
#
- platform: ping
  name: Ping Art
  host: !secret user1_url
  count: 2
  scan_interval: 30
#
- platform: ping
  name: Ping Steff
  host: !secret user0_url
  count: 2
  scan_interval: 30
#
- platform: ping
  name: Ping Rachio Controller
  host: !secret rachio_url
  scan_interval: 300
#
- platform: ping
  name: Ping Sunroom Sonos
  host: !secret sonos_black_url
  scan_interval: 300
#
- platform: ping
  name: Ping Bedroom Sonos
  host: !secret sonos_white_url
  scan_interval: 300
#
- platform: ping
  name: Ping Sonos Connect
  host: !secret sonos_connect_url
  scan_interval: 300
#
- platform: ping
  name: Ping Flux LED LightStrip
  host: !secret flux_led_url
  scan_interval: 300
#
- platform: ping
  name: Ping Sleep Number Bed
  host: 192.168.0.111
  scan_interval: 600
#
- platform: ping
  name: Ping LIFX Porch
  host: 192.168.0.93
  scan_interval: 600
#
- platform: ping
  name: Ping LIFX TV Left
  host: 192.168.0.106
  scan_interval: 600
#
- platform: ping
  name: Ping LIFX TV Right
  host: 192.168.0.182
  scan_interval: 600
#
- platform: ping
  name: Ping LIFX Garage East
  host: 192.168.0.89
  scan_interval: 600
#
- platform: ping
  name: Ping LIFX Garage Center
  host: 192.168.0.49
  scan_interval: 600
#
- platform: ping
  name: Ping LIFX Garage West
  host: 192.168.0.157
  scan_interval: 600
#
#########################
#   Bayesian Sensors    #
#########################
#
- platform: 'bayesian'
  device_class: 'presence'
  prior: 0.20
  # was 25 prior to Icloud fail
  name: 'Art Presence'
  probability_threshold: 0.90
  observations:
    - platform: 'state'
      to_state: 'home'
      entity_id: 'device_tracker.art_ot1'
      prob_given_true: 0.95
      prob_given_false: 0.05
    - platform: 'state'
      to_state: 'home'
      entity_id: 'device_tracker.arts_iphone_8'
      prob_given_true: 0.95
      prob_given_false: 0.05
    - platform: 'numeric_state'
      entity_id: 'proximity.art_to_home'
      prob_given_true: 0.90
      prob_given_false: 0.10
      below: 1
#    - platform: 'state'
#      to_state: 'on'
#      entity_id: 'binary_sensor.ping_art'
#      prob_given_true: 0.70
#      prob_given_false: 0.30
#
- platform: 'bayesian'
  device_class: 'presence'
  prior: 0.20
  name: 'Steff Presence'
  probability_threshold: 0.90
  observations:
    - platform: 'state'
      to_state: 'home'
      entity_id: 'device_tracker.steff_ot2'
      prob_given_true: 0.95
      prob_given_false: 0.05
    - platform: 'state'
      to_state: 'home'
      entity_id: 'device_tracker.steffs_iphone_8'
      prob_given_true: 0.95
      prob_given_false: 0.05
    - platform: 'numeric_state'
      entity_id: 'proximity.steff_to_home'
      prob_given_true: 0.90
      prob_given_false: 0.10
      below: 1
#    - platform: 'state'
#      to_state: 'on'
#      entity_id: 'binary_sensor.ping_steff'
#      prob_given_true: 0.70
#      prob_given_false: 0.30
#
- platform: 'bayesian'
#  device_class: 'moisture'
  prior: 0.10
  name: 'Its Raining'
  probability_threshold: 0.85
  observations:
    - platform: template
      value_template: >
        {{ 'rain' in (states.weather.dark_sky.state) }}
      prob_given_true: 0.9
      prob_given_false: 0.1
    - platform: 'state'
      to_state: 'rain'
      entity_id: 'sensor.dark_sky_icon'
      prob_given_true: 0.8
      prob_given_false: 0.2
    - platform: 'state'
      to_state: 'rain'
      entity_id: 'sensor.dark_sky_icon_0d'
      prob_given_true: 0.70
      prob_given_false: 0.30
    - platform: 'numeric_state'
      above: 90
      entity_id: 'sensor.dark_sky_precip_probability'
      prob_given_true: 0.95
      prob_given_false: 0.05
    - platform: 'numeric_state'
      above: 75
      entity_id: 'sensor.dark_sky_precip_probability_0d'
      prob_given_true: 0.70
      prob_given_false: 0.30
    - platform: template
      value_template: >
        {{ 'rain' in (states('sensor.dark_sky_summary')) }}
      prob_given_true: 0.8
      prob_given_false: 0.2
    - platform: template
      value_template: >
        {{ 'rain' in (states('sensor.dark_sky_summary_0d')) }}
      prob_given_true: 0.70
      prob_given_false: 0.30
    - platform: 'numeric_state'
      above: 0
      below: 5
      entity_id: 'sensor.dark_sky_nearest_storm_distance'
      prob_given_true: 0.80
      prob_given_false: 0.20
#
# Dark Sky icons as of 2/20/2019: clear-day, clear-night, rain, snow, sleet, wind, fog, cloudy, partly-cloudy-day, or partly-cloudy-night
#
